const menu = [
  {
    id: '1',
    mpid: '-1',
    icon: 'pay-circle-o',
    name: '收费管理',
  },
  {
    id: '2',
    bpid: '1',
    name: '前台收费',
    icon: 'pay-circle-o',
  },
  {
    id: '21',
    mpid: '2',
    bpid: '2',
    name: '日常收费',
    route: '/ChargeFeesWizard',
  },
  {
    id: '22',
    mpid: '2',
    bpid: '2',
    name: '预收费',
    route: '/CustomerAccount',
  },
  {
    id: '23',
    mpid: '2',
    bpid: '2',
    name: '经营性收费',
    route: '/TemporaryCharge',
  },
  {
    id: '24',
    mpid: '2',
    bpid: '2',
    name: '交款申请',
    route: '/AccountStatement',
  },
  {
    id: '25',
    mpid: '2',
    bpid: '2',
    name: '收费历史记录',
    route: '/PaymentHistory',
  },
  {
    id: '26',
    mpid: '2',
    bpid: '2',
    name: '损毁票据登记',
    route: '/InvalidTicket',
  },
  {
    id: '27',
    mpid: '2',
    bpid: '2',
    name: '已收费用日报',
    route: '/DayPaymentHistoryReport',
  },
  {
    id: '27',
    mpid: '2',
    bpid: '2',
    name: '客户零头账户明细',
    route: '/CustomerSmallChangeAccount',
  },
  {
    id: '3',
    bpid: '1',
    name: '应收管理',
    icon: 'calculator',
  },
  {
    id: '31',
    mpid: '3',
    bpid: '3',
    name: '已出账单',
    route: '/ReceivableListDetailReport',
  },
  {
    id: '32',
    mpid: '3',
    bpid: '3',
    name: '未出账单',
    route: '/GenerateBill',
  },
  {
    id: '33',
    mpid: '3',
    bpid: '3',
    name: '费用减免',
    route: '/FeeDiscount',
  },
  {
    id: '34',
    mpid: '3',
    bpid: '3',
    name: '费用减免明细',
    route: '/FeeDiscountReport',
  },
  {
    id: '35',
    mpid: '3',
    bpid: '3',
    name: '房间固定金额分摊',
    route: '/CostAllocation',
  },
  {
    id: '4',
    bpid: '1',
    name: '抄表管理',
    icon: 'tool',
  },
  {
    id: '41',
    mpid: '4',
    bpid: '4',
    name: '仪表类型',
    route: '/MeterType',
  },
  {
    id: '42',
    mpid: '4',
    bpid: '4',
    name: '房间仪表管理',
    route: '/HouseMeter',
  },
  {
    id: '43',
    mpid: '4',
    bpid: '4',
    name: '房间仪表抄表',
    route: '/HouseMeterReading',
  },
  {
    id: '44',
    mpid: '4',
    bpid: '4',
    name: '公摊仪表管理',
    route: '/PublicMeter',
  },
  {
    id: '44',
    mpid: '4',
    bpid: '4',
    name: '公摊仪表抄表录入',
    route: '/PublicMeterData',
  },
  {
    id: '5',
    bpid: '1',
    name: '退款管理',
    icon: 'red-envelope',
  },
  {
    id: '51',
    mpid: '5',
    bpid: '5',
    name: '新建退款',
    route: '/Deposit',
  },
  {
    id: '52',
    mpid: '5',
    bpid: '5',
    name: '退款历史',
    route: '/Refund',
  },

  {
    id: '6',
    bpid: '1',
    name: '收费参数设置',
    icon: 'setting',
  },
  {
    id: '61',
    mpid: '6',
    bpid: '6',
    name: '收费项目类别',
    route: '/ChargeItemCategory',
  },
  {
    id: '62',
    mpid: '6',
    bpid: '6',
    name: '收费项目定义',
    route: '/ChargeItemType',
  },
  {
    id: '63',
    mpid: '6',
    bpid: '6',
    name: '收费标准设置',
    route: '/ChargeItem',
  },
  {
    id: '64',
    mpid: '6',
    bpid: '6',
    name: '绑定收费标准',
    route: '/HouseChargeSetting',
  },
  {
    id: '65',
    mpid: '6',
    bpid: '6',
    name: '自动账单日设置',
    route: '/AutoGenerateBillSetting',
  },

  {
    id: '7',
    bpid: '1',
    name: '财务管理',
    icon: 'credit-card',
  },
  {
    id: '71',
    mpid: '7',
    bpid: '7',
    name: '票据管理',
  },
  {
    id: '711',
    mpid: '71',
    bpid: '71',
    name: '票据本管理',
    route: '/Ticket',
  },
  {
    id: '712',
    mpid: '71',
    bpid: '71',
    name: '当前在用票据',
    route: '/CurrentUsedTicket',
  },
  {
    id: '72',
    mpid: '7',
    bpid: '7',
    name: '交款审批',
    route: '/AccountStatement',
  },
  {
    id: '8',
    bpid: '1',
    name: '财务汇总统计报表',
    icon: 'bar-chart',
  },
  {
    id: '81',
    mpid: '8',
    bpid: '8',
    name: '费用报表',
  },
  {
    id: '811',
    mpid: '81',
    bpid: '81',
    name: '综合报表',
    route: '/ComprehensiveFinancialReport',
  },
  {
    id: '812',
    mpid: '81',
    bpid: '81',
    name: '现金收款明细',
    route: '/CashPayDetailReport',
  },
  {
    id: '813',
    mpid: '81',
    bpid: '81',
    name: '预收转实收明细',
    route: '/AdvancePayDetailReport',
  },
  {
    id: '814',
    mpid: '81',
    bpid: '81',
    name: '微信支付明细',
    route: '/WeChatPayDetailReport',
  },
  {
    id: '815',
    mpid: '81',
    bpid: '81',
    name: '微信支付明细',
    route: '/WeChatPayDetailReport',
  },
  {
    id: '82',
    mpid: '8',
    bpid: '8',
    name: '月报表',
  },
  {
    id: '821',
    mpid: '82',
    bpid: '82',
    name: '应收月度统计',
    route: '/ReceivableMonthReport',
  },
  {
    id: '822',
    mpid: '82',
    bpid: '82',
    name: '欠费月度统计',
    route: '/OwningMonthReport',
  },
  {
    id: '823',
    mpid: '82',
    bpid: '82',
    name: '已收费用月统计',
    route: '/MonthPaymentHistoryReport',
  },
  {
    id: '824',
    mpid: '82',
    bpid: '82',
    name: '收入月度分摊',
    route: '/ChargeMonthReport',
  },
  {
    id: '83',
    mpid: '8',
    bpid: '8',
    name: '年度报表',
  },
  {
    id: '831',
    mpid: '83',
    bpid: '83',
    name: '收入年度统计',
    route: '/ReceivableYearReport',
  },
  {
    id: '832',
    mpid: '83',
    bpid: '83',
    name: '欠费年度统计',
    route: '/OwningYearReport',
  },
  {
    id: '833',
    mpid: '83',
    bpid: '83',
    name: '已收费用年度统计',
    route: '/ChargeYearReport',
  },
  {
    id: '834',
    mpid: '83',
    bpid: '83',
    name: '收费率年度统计',
    route: '/ChargeYearRateReport',
  },
  {
    id: '84',
    mpid: '8',
    bpid: '8',
    name: '欠费统计',
  },
  {
    id: '841',
    mpid: '84',
    bpid: '84',
    name: '欠费月度统计',
    route: '/OwningMonthReport',
  },
  {
    id: '842',
    mpid: '84',
    bpid: '84',
    name: '欠费年度统计',
    route: '/OwningYearReport',
  },
  {
    id: '85',
    mpid: '8',
    bpid: '8',
    name: '押金统计',
  },
  {
    id: '851',
    mpid: '85',
    bpid: '85',
    name: '押金收退汇总',
    route: '/DepositChargeReport',
  },
  {
    id: '852',
    mpid: '85',
    bpid: '85',
    name: '押金收退明细',
    route: '/DepositChargeDetailReport',
  },
  {
    id: '86',
    mpid: '8',
    bpid: '8',
    name: '预付款收支明细',
    route: '/AdvancePaymentIncomeAndPaidReport',
  },
  {
    id: '9',
    bpid: '1',
    name: '打印房间费用通知单',
    route: '/PrintFeeNotice',
    icon: 'printer',
  },
]

const prefix = '/Coevery.PropertyManagementSystem'

export default menu.map(item => {
  if (item.route) item.route = `${prefix}${item.route}`
  return item
})
